### ISSUE TITLE
documentation of ethereum protocol itself

### ISSUE THREAD

**Issue by skgbanga** [rust-blockchain/evm#29]
Hi,

I am trying to read the code, and have a very basic question: Is there a good place where ethereum protocol itself is well documented, and which this code adheres to? I have tried reading ethereum yellow paper, but it is not straightforward how this code maps to that. 

To take a concrete example, consider this:

```ru
	pub fn transact_call(
		&mut self,
		caller: H160,
		address: H160,
		value: U256,
		data: Vec<u8>,
		gas_limit: u64,
	) -> (ExitReason, Vec<u8>) {
		let transaction_cost = gasometer::call_transaction_cost(&data);
		match self.state.metadata_mut().gasometer.record_transaction(transaction_cost) {
			Ok(()) => (),
			Err(e) => return (e.into(), Vec::new()),

```

The first thing `transact_call` does is calculate the call transaction cost (by calculating 0 characters and non zero characters in data and multiplying by their corresponding gas cost) and records that in gasometer. (this increments `used_gas` field). 

My basic question is where is this behavior documented, that this has to be done in this way. 

Thanks.

**Comment by JoshOrndorff** [comment]
The yellow paper is the right answer
![image](https://user-images.githubusercontent.com/2915325/117980693-3aa30200-b302-11eb-9507-ddbe348b63c1.png)

**Comment by skgbanga** [comment]
Thanks @JoshOrndorff. I am guessing the first implementation from yellow paper must be hard.
