### ISSUE TITLE
absence of nonce in transact_call

### ISSUE THREAD

**Issue by skgbanga** [rust-blockchain/evm#30]
Hello,

I was going through ethereum's yellow paper (https://ethereum.github.io/yellowpaper/paper.pdf) and it is mentioned that all transactions have a number of common fields:

> nonce: A scalar value equal to the number of transactions sent by the sender

Looking at `transact_call` here:
https://github.com/rust-blockchain/evm/blob/5150c3cc100b7faea8c1976ecfaa6602e2044325/src/executor/stack/mod.rs#L230

there is no `nonce` specified in the call, and after checking initial gas usage, we immediately increment the nonce for that account in state:

> self.state.inc_nonce(caller);

Why doesn't this function take a nonce as an argument (and check against state's nonce)? Are these functions supposed to be called by some other API which does take nonce?

**Comment by AsceticBear** [comment]
The EVM in this repo mainly used by [Frontier](https://github.com/paritytech/frontier), an Ethereum compatibility layer for Substrate. There is a [wrapper evm pallet](https://github.com/paritytech/frontier/tree/master/frame/evm) in frontier which responsible for evm execution process. 

Indeed, there is no `nonce` specified in `transact_call` or `transact_create` arguments, the nonce check can be found here https://github.com/paritytech/frontier/blob/master/frame/evm/src/runner/stack.rs#L83. 

I hope this information can be helpful.

**Comment by skgbanga** [comment]
This helps a lot! Thanks @AsceticBear 

I will try to read more into Frontier and how it is using this evm. Any help in that regard is appreciated.

**Comment by skgbanga** [comment]
https://www.youtube.com/watch?v=U18uEgWVZy4

This helped a lot.
